// src/components/AdminRoomDispatching.jsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import OceanBackground from './OceanBackground';
import AudioControl from './AudioControl';

export default function AdminRoomDispatching() {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [successMessage, setSuccessMessage] = useState(null);
  
  // Admin verification
  const [isAdmin, setIsAdmin] = useState(false);
  const [adminCode, setAdminCode] = useState('');
  
  // Room management data
  const [allRooms, setAllRooms] = useState(() => {
    const saved = localStorage.getItem('dynamicRoomsData');
    return saved ? JSON.parse(saved) : {};
  });
  
  const [users, setUsers] = useState(() => {
    const saved = localStorage.getItem('allUsers');
    return saved ? JSON.parse(saved) : [];
  });

  // Check admin access on component mount
  useEffect(() => {
    const adminAccess = sessionStorage.getItem('adminAccess');
    const accessCode = sessionStorage.getItem('accessCode');
    
    if (adminAccess === 'admin' && accessCode) {
      setIsAdmin(true);
      setAdminCode(accessCode);
    } else {
      // Redirect non-admins
      navigate('/');
    }
  }, [navigate]);

  // Save data when changed
  useEffect(() => {
    localStorage.setItem('dynamicRoomsData', JSON.stringify(allRooms));
  }, [allRooms]);

  useEffect(() => {
    localStorage.setItem('allUsers', JSON.stringify(users));
  }, [users]);

  // Admin functions
  const clearAllRooms = () => {
    if (window.confirm('⚠️ Are you sure you want to clear ALL rooms? This cannot be undone!')) {
      setAllRooms({});
      localStorage.removeItem('dynamicRoomsData');
      setSuccessMessage('✅ All rooms cleared successfully');
      setTimeout(() => setSuccessMessage(null), 3000);
    }
  };

  const exportData = () => {
    const data = {
      rooms: allRooms,
      users: users,
      exportDate: new Date().toISOString(),
      exportedBy: adminCode
    };
    
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `room-data-${new Date().toISOString().split('T')[0]}.json`;
    a.click();
    URL.revokeObjectURL(url);
    
    setSuccessMessage('✅ Data exported successfully');
    setTimeout(() => setSuccessMessage(null), 3000);
  };

  const generateReport = () => {
    const totalRooms = Object.keys(allRooms).length;
    const totalUsers = Object.values(allRooms).reduce((acc, room) => acc + room.members.length, 0);
    const occupancyRate = totalRooms > 0 ? ((totalUsers / (totalRooms * 4)) * 100).toFixed(1) : 0;
    
    const report = `
📊 BEPS 2026 ROOM DISPATCHING REPORT
Generated: ${new Date().toLocaleString()}
Generated by: ${adminCode}

🏴‍☠️ OVERVIEW:
- Total Quarters: ${totalRooms}
- Total Crew Members: ${totalUsers}
- Average Occupancy: ${occupancyRate}%

🏢 ROOM BREAKDOWN:
${Object.entries(allRooms).map(([roomId, room]) => 
  `- ${room.name} (${room.code}): ${room.members.length}/${room.capacity} crew`
).join('\n')}

👥 CREW ROSTER:
${Object.values(allRooms).flatMap(room => 
  room.members.map(member => `- ${member.name} (${member.position}) in ${room.name}`)
).join('\n')}
    `.trim();
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `room-report-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    
    setSuccessMessage('✅ Report generated successfully');
    setTimeout(() => setSuccessMessage(null), 3000);
  };

  const kickUser = (roomId, userId) => {
    if (window.confirm('Are you sure you want to remove this crew member?')) {
      setAllRooms(prev => {
        const updated = { ...prev };
        const room = updated[roomId];
        
        if (room) {
          room.members = room.members.filter(member => member.id !== userId);
          
          // Delete room if empty
          if (room.members.length === 0) {
            delete updated[roomId];
          }
        }
        
        return updated;
      });
      
      setSuccessMessage('✅ Crew member removed');
      setTimeout(() => setSuccessMessage(null), 3000);
    }
  };

  if (!isAdmin) {
    return (
      <>
        <OceanBackground />
        <div style={{
          position: 'absolute', top: '50%', left: '50%', 
          transform: 'translate(-50%, -50%)', textAlign: 'center',
          color: '#FFD700', fontFamily: "'Pieces of Eight', serif"
        }}>
          <h1>🏴‍☠️ Access Denied</h1>
          <p>Only captains can access these waters...</p>
        </div>
      </>
    );
  }

  const totalRooms = Object.keys(allRooms).length;
  const totalUsers = Object.values(allRooms).reduce((acc, room) => acc + room.members.length, 0);
  const occupancyRate = totalRooms > 0 ? ((totalUsers / (totalRooms * 4)) * 100).toFixed(1) : 0;

  return (
    <>
      <OceanBackground />
      
      <div style={{ position: 'fixed', top: 28, right: 28, zIndex: 100 }}>
        <img src="/assets/logo.png" alt="Stand Up 2K26" style={{ width: 120, filter: "drop-shadow(0 4px 12px rgba(0,0,0,0.7))" }} />
      </div>

      <AudioControl />

      {/* Back Button */}
      <button 
        onClick={() => navigate('/')} 
        style={{
          position: 'fixed', top: '20px', left: '20px', zIndex: 100,
          background: '#FFD700', color: '#08161B',
          border: '3px solid #08161B', padding: '12px 24px', borderRadius: '12px',
          cursor: 'pointer', fontFamily: "'Pieces of Eight', serif", fontSize: '16px',
          fontWeight: 'bold', textTransform: 'uppercase'
        }}
      >
        ← Back to Harbor
      </button>

      {/* Admin Badge */}
      <div style={{
        position: 'fixed', top: '20px', right: '160px', zIndex: 99,
        background: 'linear-gradient(135deg, #FFD700 0%, #FFA000 100%)',
        color: '#08161B', padding: '10px 20px', borderRadius: '10px',
        border: '3px solid #08161B', fontFamily: "'Pieces of Eight', serif",
        fontSize: '14px', fontWeight: 'bold', textTransform: 'uppercase'
      }}>
        👑 CAPTAIN {adminCode}
      </div>

      {/* Messages */}
      {error && (
        <div style={{
          position: 'fixed', top: '80px', left: '50%', transform: 'translateX(-50%)',
          background: 'rgba(255, 59, 48, 0.9)', color: 'white', padding: '15px 25px',
          borderRadius: '10px', zIndex: 200, fontWeight: 'bold'
        }}>
          ⚠️ {error}
        </div>
      )}
      
      {successMessage && (
        <div style={{
          position: 'fixed', top: '80px', left: '50%', transform: 'translateX(-50%)',
          background: 'rgba(76, 175, 80, 0.9)', color: 'white', padding: '15px 25px',
          borderRadius: '10px', zIndex: 200, fontWeight: 'bold'
        }}>
          {successMessage}
        </div>
      )}

      <div style={{
        position: 'relative', zIndex: 10, minHeight: '100vh', padding: '100px 2rem 2rem',
        color: 'white'
      }}>
        <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
          {/* Header */}
          <div style={{ textAlign: 'center', marginBottom: '40px' }}>
            <h1 style={{
              color: '#FFD700', fontFamily: "'Pieces of Eight', serif",
              fontSize: '3rem', marginBottom: '1rem'
            }}>
              🏴‍☠️ Captain's Room Control
            </h1>
            <p style={{ color: '#B7A98A', fontSize: '1.2rem' }}>
              Master control for all crew quarters aboard BEPS 2026
            </p>
          </div>
          {/* Stats Dashboard */}
          <div style={{
            display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
            gap: '20px', marginBottom: '40px'
          }}>
            <div style={{
              background: 'rgba(8, 22, 27, 0.9)', border: '2px solid #FFD700',
              borderRadius: '15px', padding: '25px', textAlign: 'center'
            }}>
              <h3 style={{ color: '#FFD700', fontSize: '2.5rem', margin: '0' }}>{totalRooms}</h3>
              <p style={{ color: '#B7A98A', margin: '5px 0 0' }}>🏢 Total Quarters</p>
            </div>
            <div style={{
              background: 'rgba(8, 22, 27, 0.9)', border: '2px solid #4CAF50',
              borderRadius: '15px', padding: '25px', textAlign: 'center'
            }}>
              <h3 style={{ color: '#4CAF50', fontSize: '2.5rem', margin: '0' }}>{totalUsers}</h3>
              <p style={{ color: '#B7A98A', margin: '5px 0 0' }}>👥 Total Crew</p>
            </div>
            <div style={{
              background: 'rgba(8, 22, 27, 0.9)', border: '2px solid #FF9800',
              borderRadius: '15px', padding: '25px', textAlign: 'center'
            }}>
              <h3 style={{ color: '#FF9800', fontSize: '2.5rem', margin: '0' }}>{occupancyRate}%</h3>
              <p style={{ color: '#B7A98A', margin: '5px 0 0' }}>📊 Occupancy</p>
            </div>
          </div>

          {/* Admin Actions */}
          <div style={{
            background: 'rgba(8, 22, 27, 0.9)', border: '2px solid #FFD700',
            borderRadius: '20px', padding: '30px', marginBottom: '40px'
          }}>
            <h2 style={{ color: '#FFD700', fontFamily: "'Pieces of Eight', serif", marginBottom: '25px' }}>
              ⚓ Captain's Commands
            </h2>
            <div style={{ display: 'flex', gap: '15px', flexWrap: 'wrap' }}>
              <button
                onClick={generateReport}
                style={{
                  padding: '12px 25px', background: '#4CAF50', color: 'white',
                  border: 'none', borderRadius: '10px', cursor: 'pointer',
                  fontFamily: "'Pieces of Eight', serif", fontSize: '16px', fontWeight: 'bold'
                }}
              >
                📋 Generate Report
              </button>
              <button
                onClick={exportData}
                style={{
                  padding: '12px 25px', background: '#2196F3', color: 'white',
                  border: 'none', borderRadius: '10px', cursor: 'pointer',
                  fontFamily: "'Pieces of Eight', serif", fontSize: '16px', fontWeight: 'bold'
                }}
              >
                💾 Export Data
              </button>
              <button
                onClick={() => navigate('/room-dispatching/shared')}
                style={{
                  padding: '12px 25px', background: '#FF9800', color: 'white',
                  border: 'none', borderRadius: '10px', cursor: 'pointer',
                  fontFamily: "'Pieces of Eight', serif", fontSize: '16px', fontWeight: 'bold'
                }}
              >
                🏢 View User Interface
              </button>
              <button
                onClick={clearAllRooms}
                style={{
                  padding: '12px 25px', background: '#F44336', color: 'white',
                  border: 'none', borderRadius: '10px', cursor: 'pointer',
                  fontFamily: "'Pieces of Eight', serif", fontSize: '16px', fontWeight: 'bold'
                }}
              >
                🗑️ Clear All Rooms
              </button>
            </div>
          </div>

          {/* Rooms Management */}
          <div style={{
            background: 'rgba(8, 22, 27, 0.9)', border: '2px solid #FFD700',
            borderRadius: '20px', padding: '30px'
          }}>
            <h2 style={{ color: '#FFD700', fontFamily: "'Pieces of Eight', serif", marginBottom: '25px' }}>
              🏴‍☠️ Active Quarters ({totalRooms})
            </h2>
            
            {Object.keys(allRooms).length === 0 ? (
              <div style={{ textAlign: 'center', padding: '40px', color: '#B7A98A' }}>
                <p style={{ fontSize: '1.2rem' }}>🏜️ No quarters have been established yet</p>
                <p>Crew members will create quarters as they board the ship</p>
              </div>
            ) : (
              <div style={{ display: 'grid', gap: '20px' }}>
                {Object.entries(allRooms).map(([roomId, room]) => (
                  <div key={roomId} style={{
                    background: 'rgba(23, 66, 74, 0.3)', border: '1px solid rgba(255, 215, 0, 0.3)',
                    borderRadius: '15px', padding: '20px'
                  }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '15px' }}>
                      <div>
                        <h3 style={{ color: '#FFD700', margin: '0 0 5px 0' }}>{room.name}</h3>
                        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
                          <span style={{ color: '#4CAF50', fontWeight: 'bold' }}>📍 {room.code}</span>
                          <span style={{ color: '#B7A98A' }}>👥 {room.members.length}/{room.capacity}</span>
                          <span style={{ color: '#B7A98A' }}>🎖️ {room.position}</span>
                          <span style={{ color: '#B7A98A' }}>👫 {room.gender}</span>
                        </div>
                      </div>
                      <div style={{
                        color: room.members.length >= room.capacity ? '#F44336' : '#4CAF50',
                        fontWeight: 'bold', fontSize: '0.9rem'
                      }}>
                        {room.members.length >= room.capacity ? '🔒 FULL' : `🆓 ${room.capacity - room.members.length} SPOTS`}
                      </div>
                    </div>
                    
                    {/* Crew Members */}
                    <div>
                      <h4 style={{ color: '#FFD700', margin: '0 0 10px 0' }}>⚓ Crew Roster:</h4>
                      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '10px' }}>
                        {room.members.map((member, idx) => (
                          <div key={idx} style={{
                            display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                            background: 'rgba(255, 215, 0, 0.1)', padding: '10px 15px', borderRadius: '8px'
                          }}>
                            <div>
                              <span style={{ color: '#FFD700', fontWeight: 'bold' }}>{member.name}</span>
                              <span style={{ color: '#B7A98A', marginLeft: '10px' }}>({member.position})</span>
                            </div>
                            <button
                              onClick={() => kickUser(roomId, member.id)}
                              style={{
                                background: '#F44336', color: 'white', border: 'none',
                                padding: '5px 10px', borderRadius: '5px', cursor: 'pointer',
                                fontSize: '12px', fontWeight: 'bold'
                              }}
                            >
                              ❌ Remove
                            </button>
                          </div>
                        ))}
                      </div>
                    </div>
                    
                    {/* Room Actions */}
                    <div style={{ marginTop: '15px', paddingTop: '15px', borderTop: '1px solid rgba(255, 215, 0, 0.3)' }}>
                      <small style={{ color: '#A89A7A' }}>
                        📅 Created: {new Date(room.createdAt).toLocaleString()} | 
                        👑 By: {room.createdBy || 'Unknown'}
                      </small>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Footer */}
          <div style={{ textAlign: 'center', marginTop: '40px', color: '#A89A7A' }}>
            <p>🏴‍☠️ BEPS 2026 Captain's Control Panel | Logged in as: {adminCode}</p>
          </div>
        </div>
      </div>
    </>
  );
}